// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssetOrigin } from "./AssetOrigin";
import type { Filmstrip } from "./Filmstrip";
import type { MediaKind } from "./MediaKind";
import type { MediaMeta } from "./MediaMeta";
import type { Waveform } from "./Waveform";

export type Asset = { id: string, name: string, kind: MediaKind, 
/**
 * Absolute path to the source file.
 */
path: string, meta: MediaMeta, origin: AssetOrigin, created_at: string, 
/**
 * Small poster image for the library.
 */
thumbnail: string | null, 
/**
 * Horizontal strip of frames used to draw clips on the timeline.
 */
filmstrip: Filmstrip | null, 
/**
 * Audio peaks file (little-endian f32, `peaks_per_second` values per second).
 */
waveform: Waveform | null, 
/**
 * Browser-friendly transcode used by the preview when the source codec isn't playable.
 */
proxy: string | null, };
