// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TextStyle } from "./TextStyle";
import type { Transform } from "./Transform";

/**
 * Partial update for a clip. `None` fields are left untouched.
 */
export type ClipPatch = { name?: string, transform?: Transform, volume?: number, fade_in?: number, fade_out?: number, speed?: number, text?: TextStyle, color?: string, };
