// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClipContent } from "./ClipContent";
import type { Transform } from "./Transform";

export type Clip = { id: string, name: string, 
/**
 * Timeline position of the first frame.
 */
start: number, 
/**
 * Length on the timeline (already accounts for speed).
 */
duration: number, 
/**
 * Offset into the source media, in source seconds.
 */
in_point: number, speed: number, content: ClipContent, transform: Transform, volume: number, fade_in: number, fade_out: number, };
