// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MediaKind } from "./MediaKind";
import type { TextStyle } from "./TextStyle";

export type ClipContent = { "type": "media", asset_id: string, } | { "type": "text", style: TextStyle, } | { "type": "solid", color: string, } | { "type": "pending", job_id: string, kind: MediaKind, prompt: string, model_name: string, };
