// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EditOutcome } from "./EditOutcome";
import type { ProjectView } from "./ProjectView";

export type EditResponse = { view: ProjectView, outcome: EditOutcome, };
