// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Asset } from "./Asset";
import type { Clip } from "./Clip";
import type { ClipMove } from "./ClipMove";
import type { ClipPatch } from "./ClipPatch";
import type { Edge } from "./Edge";
import type { ProjectSettings } from "./ProjectSettings";
import type { TrackKind } from "./TrackKind";
import type { TrackPatch } from "./TrackPatch";

export type Edit = { "op": "rename_project", name: string, } | { "op": "set_settings", settings: ProjectSettings, } | { "op": "add_asset", asset: Asset, } | { "op": "update_asset", asset: Asset, } | { "op": "remove_asset", asset_id: string, } | { "op": "add_track", kind: TrackKind, index: number | null, } | { "op": "remove_track", track_id: string, } | { "op": "update_track", track_id: string, patch: TrackPatch, } | { "op": "move_track", track_id: string, index: number, } | { "op": "insert_asset", asset_id: string, track_id: string | null, start: number, } | { "op": "add_clip", track_id: string | null, clip: Clip, } | { "op": "move_clips", moves: Array<ClipMove>, } | { "op": "trim_clip", clip_id: string, edge: Edge, time: number, } | { "op": "split", time: number, clip_ids: Array<string> | null, } | { "op": "delete_clips", clip_ids: Array<string>, ripple: boolean, } | { "op": "duplicate_clips", clip_ids: Array<string>, } | { "op": "update_clip", clip_id: string, patch: ClipPatch, } | { "op": "close_gap", track_id: string, time: number, } | { "op": "resolve_pending", job_id: string, asset_id: string, } | { "op": "drop_pending", job_id: string, } | { "op": "add_marker", time: number, label: string, } | { "op": "remove_marker", marker_id: string, };
