// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What an edit produced, useful for the UI to select new things.
 */
export type EditOutcome = { created_clips: Array<string>, created_tracks: Array<string>, };
