// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExportFormat } from "./ExportFormat";
import type { Quality } from "./Quality";

export type ExportSettings = { path: string, format: ExportFormat, quality: Quality, 
/**
 * Output size; defaults to the project size.
 */
width: number | null, height: number | null, fps: number | null, 
/**
 * Only render this range (seconds).
 */
range: [number, number] | null, };
