// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Filmstrip = { path: string, 
/**
 * Number of frames laid out left to right in the strip.
 */
frames: number, frame_width: number, frame_height: number, 
/**
 * Seconds between two frames.
 */
interval: number, };
