// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InputImage } from "./InputImage";
import type { Task } from "./Task";

/**
 * A generation request, independent of any provider.
 */
export type GenRequest = { model: string, task: Task, prompt: string, negative_prompt: string | null, images: Array<InputImage>, 
/**
 * `"16:9"`, `"1:1"`, … Providers map it to the closest supported value.
 */
aspect_ratio: string | null, 
/**
 * Exact pixel size, for providers that take one. Usually the project size.
 */
width: number | null, height: number | null, 
/**
 * Seconds (video).
 */
duration: number | null, resolution: string | null, seed: number | null, 
/**
 * Number of outputs wanted.
 */
count: number, 
/**
 * Generate sound with the video when the model can.
 */
audio: boolean | null, 
/**
 * Model-specific values keyed by [`ParamSpec::key`].
 */
params: Record<string, unknown>, };
