// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImageRole } from "./ImageRole";

/**
 * An image handed to a model. The editor fills `path`; the harness loads `data`.
 */
export type InputImage = { role: ImageRole, path: string, mime: string, };
