// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GenRequest } from "./GenRequest";
import type { JobStatus } from "./JobStatus";
import type { Progress } from "./Progress";
import type { SavedOutput } from "./SavedOutput";

/**
 * A job as the UI sees it. Every change is broadcast as a full snapshot.
 */
export type Job = { id: string, provider: string, model: string, model_name: string, request: GenRequest, status: JobStatus, progress: Progress, created_at: string, finished_at: string | null, elapsed_ms: number, outputs: Array<SavedOutput>, error: string | null, seed: number | null, cost_usd: number | null, 
/**
 * Free-form tag the editor uses to remember what to do with the result
 * (e.g. which placeholder clip to replace).
 */
tag: unknown, };
