// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MediaMeta = { duration: number | null, width: number | null, height: number | null, fps: number | null, has_video: boolean, has_audio: boolean, video_codec: string | null, audio_codec: string | null, size_bytes: bigint, };
