// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ParamSpec } from "./ParamSpec";
import type { Task } from "./Task";

/**
 * One model a provider can run.
 */
export type ModelInfo = { 
/**
 * Provider-specific id sent back in [`GenRequest::model`].
 */
id: string, name: string, provider: string, tasks: Array<Task>, description: string | null, 
/**
 * Supported aspect ratios like `"16:9"`. Empty means any size via width/height.
 */
aspect_ratios: Array<string>, 
/**
 * Supported clip lengths in seconds (video). Empty means the model decides.
 */
durations: Array<number>, 
/**
 * Supported output resolutions like `"720p"`, `"1080p"`, `"1K"`.
 */
resolutions: Array<string>, 
/**
 * How many outputs one request can return.
 */
max_outputs: number, negative_prompt: boolean, seed: boolean, 
/**
 * Can be given an end frame in addition to the start frame (image-to-video).
 */
end_frame: boolean, 
/**
 * Max reference images for image-to-image / image-to-video.
 */
max_images: number, 
/**
 * Produces sound along with the video.
 */
audio: boolean, params: Array<ParamSpec>, 
/**
 * Human hint like `"≈ $0.04 / image"`.
 */
price: string | null, 
/**
 * Shown first in pickers.
 */
featured: boolean, };
