// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ParamKind } from "./ParamKind";

/**
 * A model-specific knob rendered in the "Advanced" section of the generate panel.
 * Values are passed to the provider in [`GenRequest::params`] under `key`.
 */
export type ParamSpec = { key: string, label: string, kind: ParamKind, default: unknown, help: string | null, };
