// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SelectOption } from "./SelectOption";

/**
 * Type of a model-specific knob.
 */
export type ParamKind = { "type": "int", min: number, max: number, step: number, } | { "type": "float", min: number, max: number, step: number, } | { "type": "bool" } | { "type": "select", options: Array<SelectOption>, } | { "type": "text", multiline: boolean, };
