// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a generation's result should go.
 */
export type Placement = { "type": "library" } | { "type": "timeline", track_id: string | null, start: number, duration: number, };
