// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Progress reported while a job runs.
 */
export type Progress = { 
/**
 * 0.0–1.0 when known.
 */
fraction: number | null, 
/**
 * Short status such as `"In queue (3 ahead)"` or `"Sampling 12/30"`.
 */
message: string | null, };
