// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Asset } from "./Asset";
import type { Marker } from "./Marker";
import type { ProjectSettings } from "./ProjectSettings";
import type { Track } from "./Track";

export type Project = { id: string, name: string, created_at: string, updated_at: string, settings: ProjectSettings, assets: Array<Asset>, 
/**
 * Index 0 is the top-most track (drawn last, on top).
 */
tracks: Array<Track>, markers: Array<Marker>, };
