// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Project } from "./Project";

/**
 * What the UI receives after every change.
 */
export type ProjectView = { project: Project, can_undo: boolean, can_redo: boolean, };
