// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProjectSettings = { width: number, height: number, fps: number, 
/**
 * Canvas colour as `#rrggbb`.
 */
background: string, sample_rate: number, };
