// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProjectSummary = { id: string, name: string, updated_at: string, duration: number, width: number, height: number, 
/**
 * Poster of the first visual asset, if any.
 */
cover: string | null, generated_count: number, };
