// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * User settings for one provider (persisted by the app; keys are not in here).
 */
export type ProviderSettings = { 
/**
 * Hidden from model pickers when false.
 */
enabled: boolean, 
/**
 * Overrides [`ProviderInfo::default_base_url`].
 */
base_url: string | null, options: Record<string, unknown>, };
