// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KeySource } from "./KeySource";
import type { ProviderInfo } from "./ProviderInfo";
import type { ProviderSettings } from "./ProviderSettings";

export type ProviderStatus = { info: ProviderInfo, settings: ProviderSettings, key_source: KeySource, 
/**
 * Last 4 characters of the key, for display.
 */
key_preview: string | null, 
/**
 * Usable right now: enabled, and has a key if it needs one.
 */
ready: boolean, };
