// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderKind } from "./ProviderKind";
import type { Task } from "./Task";

/**
 * Static description of a provider, shown in settings.
 */
export type ProviderInfo = { 
/**
 * Stable id, e.g. `"openrouter"`.
 */
id: string, name: string, kind: ProviderKind, 
/**
 * One line: what this provider is good for.
 */
tagline: string, website: string, 
/**
 * Whether an API key is required.
 */
needs_key: boolean, 
/**
 * Environment variables checked for a key when none is saved, in order.
 */
key_env: Array<string>, 
/**
 * Where users create a key.
 */
key_url: string | null, 
/**
 * Placeholder hint for the key field (e.g. `"sk-or-…"`).
 */
key_hint: string | null, 
/**
 * Base URL used when the user hasn't set one.
 */
default_base_url: string, 
/**
 * Local servers and self-hosted gateways let users point elsewhere.
 */
base_url_editable: boolean, tasks: Array<Task>, };
