// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OutputKind } from "./OutputKind";

/**
 * A saved output on disk.
 */
export type SavedOutput = { path: string, kind: OutputKind, mime: string, };
