// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GenRequest } from "./GenRequest";
import type { Placement } from "./Placement";

export type SubmitArgs = { provider: string, request: GenRequest, placement: Placement, 
/**
 * Library assets used as inputs, recorded for provenance.
 */
input_assets: Array<string>, };
