// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a model is asked to do.
 */
export type Task = "text_to_image" | "image_to_image" | "text_to_video" | "image_to_video";
