// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TextAlign } from "./TextAlign";

export type TextStyle = { content: string, font_family: string, 
/**
 * Pixels in project space.
 */
font_size: number, font_weight: number, italic: boolean, color: string, background: string | null, align: TextAlign, line_height: number, letter_spacing: number, shadow: boolean, };
