// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TrackPatch = { name?: string, muted?: boolean, hidden?: boolean, locked?: boolean, };
