// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Fit } from "./Fit";

export type Transform = { 
/**
 * Offset of the clip centre from the canvas centre, in project pixels.
 */
x: number, y: number, 
/**
 * 1.0 = fitted to the canvas (contain).
 */
scale: number, 
/**
 * Degrees, clockwise.
 */
rotation: number, opacity: number, fit: Fit, };
