//! `docs/COMPATIBILITY.md`, generated by `kimchi-cli docs` from the tables kimchi works from:
//! the apps people come from (`kimchi_interop::apps`), project and look formats, keyboard
//! layouts ([`crate::keymaps`]), and the AI providers. A test keeps the file in step.

use kimchi_interop::apps::{APPS, Kind};
use kimchi_interop::looks::LOOK_FORMATS;
use kimchi_interop::timeline::{FORMATS, Support};

fn support(s: Support) -> &'static str {
    match s {
        Support::No => "—",
        Support::Basic => "basic",
        Support::Good => "good",
    }
}

fn cell(s: &str) -> String {
    s.replace('|', "\\|").replace('\n', " ")
}

fn format_names(ids: &[&str]) -> String {
    if ids.is_empty() {
        return "—".into();
    }
    ids.iter().map(|id| FORMATS.iter().find(|f| f.id == *id).map(|f| f.label).unwrap_or(id)).collect::<Vec<_>>().join(", ")
}

pub fn markdown() -> String {
    let mut out = String::from(
        "# Working with other apps\n\n\
         Generated by `kimchi-cli docs` from kimchi's own tables. Do not edit by hand.\n\n\
         Coming from another editor? kimchi opens its projects, uses its looks and LUTs, and can take its keyboard shortcuts. \
         The first-run setup (Help › Set up kimchi…) does all of it for the app you choose; `app.onboarding` lists what it finds on \
         your computer. Commands: `project.importFrom`, `project.exportTo`, `looks.import`, `app.keymaps` (see [COMMANDS.md](COMMANDS.md)).\n",
    );
    for (kind, title) in [(Kind::Editor, "Video editors"), (Kind::Motion, "Motion graphics and compositing"), (Kind::Photo, "Photos and colour"), (Kind::ThreeD, "3D"), (Kind::Audio, "Sound")] {
        let apps: Vec<_> = APPS.iter().filter(|a| a.kind == kind).collect();
        if apps.is_empty() {
            continue;
        }
        out.push_str(&format!("\n## {title}\n"));
        for a in apps {
            out.push_str(&format!("\n### {} ({})\n\n", a.name, a.vendor));
            out.push_str(&format!("- **kimchi opens:** {}\n", format_names(a.opens)));
            out.push_str(&format!("- **kimchi writes for it:** {}\n", format_names(a.writes)));
            if let Some(k) = a.keymap.and_then(|k| crate::keymaps::layout(k).ok()) {
                out.push_str(&format!("- **Keyboard:** {}'s layout (`shortcuts.keymap` = `{}`). {}\n", k.name, k.id, k.notes));
            }
            out.push_str(&format!("- **Bring a project over:** {}\n", a.bring));
            out.push_str(&format!("- **Send a cut back:** {}\n", a.take));
            if !a.looks.is_empty() {
                out.push_str(&format!("- **Looks:** {}\n", a.looks));
            }
            if !a.plugins.is_empty() {
                out.push_str(&format!("- **Plugins:** {}\n", a.plugins));
            }
        }
    }
    out.push_str("\n## Project and timeline formats\n\n| Format | Files | Used by | Open | Write | Notes |\n| --- | --- | --- | --- | --- | --- |\n");
    for f in FORMATS {
        let apps: Vec<&str> = f.apps.iter().map(|id| kimchi_interop::apps::app(id).map(|a| a.name).unwrap_or(id)).collect();
        out.push_str(&format!(
            "| {} (`{}`) | {} | {} | {} | {} | {} |\n",
            f.label,
            f.id,
            f.extensions.iter().map(|e| format!(".{e}")).collect::<Vec<_>>().join(" "),
            apps.join(", "),
            support(f.import),
            support(f.export),
            cell(f.notes)
        ));
    }
    out.push_str("\n_basic_: the cut (clips, timing, tracks). _good_: the cut and most of what the format carries that kimchi has (transforms, opacity, volume, fades, transitions, titles, markers, speed).\n");
    out.push_str("\n## Looks and LUTs\n\n| Format | Files | Used by | Notes |\n| --- | --- | --- | --- |\n");
    for f in LOOK_FORMATS {
        let apps: Vec<&str> = f.apps.iter().map(|id| kimchi_interop::apps::app(id).map(|a| a.name).unwrap_or(id)).collect();
        out.push_str(&format!("| {} | {} | {} | {} |\n", f.label, f.extensions.iter().map(|e| format!(".{e}")).collect::<Vec<_>>().join(" "), apps.join(", "), cell(f.notes)));
    }
    out.push_str(
        "\n## Keyboard layouts\n\nSettings › Keyboard (or `app.setSetting shortcuts.keymap`). An action the other app has a key for takes that key; \
         the others keep kimchi's own, except keys the other app uses for something else. The Studio keeps its own keys. \
         The `?` sheet shows the keys in use; `app.keymaps` lists every layout.\n\n| Layout | Id | Keys from |\n| --- | --- | --- |\n",
    );
    for l in crate::keymaps::LAYOUTS {
        let from = if l.source.starts_with("http") { format!("[{}]({})", l.name, l.source) } else if l.source.is_empty() { "kimchi".into() } else { l.source.to_string() };
        out.push_str(&format!("| {} | `{}` | {} |\n", l.name, l.id, from));
    }
    out.push_str("\nSome keys, as they are on Windows and Linux (⌘ instead of Ctrl on a Mac):\n\n| Action | ");
    let shown = ["premiere", "finalcut", "resolve", "avid", "kdenlive", "shotcut"];
    let layouts: Vec<_> = shown.iter().filter_map(|id| crate::keymaps::layout(id).ok()).collect();
    out.push_str(&format!("kimchi | {} |\n| --- | --- |{}\n", layouts.iter().map(|l| l.name).collect::<Vec<_>>().join(" | "), " --- |".repeat(layouts.len())));
    let resolved: Vec<Vec<crate::keymaps::Binding>> = layouts.iter().map(|l| crate::keymaps::resolve(l, false)).collect();
    for name in ["PlayPause", "Split", "TrimStart", "TrimEnd", "RippleDelete", "AddMarker", "ToggleSnap", "ZoomFit", "Undo", "Redo", "Export"] {
        let Some(a) = crate::keymaps::action(name) else { continue };
        let keys = |keys: &[String]| if keys.is_empty() { "—".to_string() } else { keys.iter().take(2).map(|k| format!("`{}`", crate::keymaps::label(k, false))).collect::<Vec<_>>().join(" ") };
        let own: Vec<String> = a.keys.iter().map(|k| k.to_string()).collect();
        out.push_str(&format!("| {} | {} |", a.label, keys(&own)));
        for r in &resolved {
            let b = r.iter().find(|b| b.action == name).map(|b| keys(&b.keys)).unwrap_or_default();
            out.push_str(&format!(" {b} |"));
        }
        out.push('\n');
    }
    out.push_str("\n## Generation providers\n\nSettings › Models, or the first-run setup's \"Connect your provider\". Keys stay in the system keychain.\n\n| Provider | Kind | What for |\n| --- | --- | --- |\n");
    for p in kimchi_gen::providers::all() {
        let i = p.info();
        out.push_str(&format!("| [{}]({}) | {} | {} |\n", i.name, i.website, if matches!(i.kind, kimchi_gen::ProviderKind::Local) { "on this computer" } else { "cloud" }, cell(&i.tagline)));
    }
    out.push_str(&format!(
        "\n## The assistant\n\nThe Agent panel runs one of: {}. Settings › Agent, `agent.providers`, `agent.setProvider`. Any MCP client can drive kimchi too: `kimchi-mcp --live`.\n",
        crate::settings::AGENT_PROVIDERS.iter().map(|p| format!("`{p}`")).collect::<Vec<_>>().join(", ")
    ));
    out
}
