//! The C ABI between kimchi and a plugin library (ABI 1).
//!
//! A library exports one function, `kimchi_plugin_entry`, returning an [`Entry`]: the ABI version
//! and `plugin(index)`, which hands out one [`PluginVTable`] per plugin type. Every function in a
//! vtable is generated by [`vtable`] from a [`Plugin`] implementation, so plugin authors never
//! write `extern "C"` themselves; [`export_plugins!`](crate::export_plugins) writes the entry.
//!
//! - **Metadata** is JSON ([`Manifest`]): the plugin's [`Info`](crate::Info) and parameters.
//!   New fields can be added without a new ABI (readers ignore what they don't know).
//! - **Instances** are opaque pointers made by `create` and released by `destroy`.
//! - **Values** cross as [`RawValue`]s; the plugin side checks each against its parameter (kind,
//!   range, choices) before `set_param` sees it.
//! - **Frames** are [`RawFrame`]s: premultiplied RGBA8 rows with a stride.
//! - **The host** lends services in [`RawHost`] (its thread pool, its log) to every `render`.
//! - **Panics** never cross: each call catches them. A plugin that panicked is *poisoned*: it
//!   answers [`STATUS_POISONED`] from then on, `last_error` says why, and the host shows the
//!   picture unchanged.
//!
//! Growing the ABI: [`PluginVTable`], [`RawRenderCtx`], [`RawSetup`] and [`RawHost`] start with
//! their own `size`. A later SDK may append fields; a reader uses only the fields that fit in the
//! size it was given, so an old host loads a new plugin and a new host loads an old one. A
//! change to existing fields would be ABI 2, under the same entry symbol with a new
//! `abi_version`, which hosts refuse until they know it.

use std::any::Any;
use std::ffi::c_void;
use std::panic::AssertUnwindSafe;
use std::sync::Mutex;

use serde::{Deserialize, Serialize};

use crate::frame::{Frame, FrameMut};
use crate::plugin::{Initial, Kind, Param, ParamKind, Plugin, RenderCtx, Setup, Value};
use crate::ABI_VERSION;

/// The call worked.
pub const STATUS_OK: i32 = 0;
/// The host passed something wrong (a null pointer, a frame of the wrong size, a value of the
/// wrong kind); nothing happened. `last_error` says what.
pub const STATUS_INVALID: i32 = 1;
/// The plugin panicked in this call. It is poisoned now; `last_error` has the panic's message.
pub const STATUS_PANICKED: i32 = 2;
/// The plugin panicked in an earlier call and isn't called any more.
pub const STATUS_POISONED: i32 = 3;

/// [`RawFrame::format`]: premultiplied RGBA, 8 bits per channel, sRGB. The only format of ABI 1.
pub const FORMAT_RGBA8_PREMULTIPLIED: u32 = 0;

/// [`RawValue::kind`]s.
pub const VALUE_NUMBER: u32 = 0;
pub const VALUE_INTEGER: u32 = 1;
pub const VALUE_TOGGLE: u32 = 2;
pub const VALUE_CHOICE: u32 = 3;
pub const VALUE_COLOR: u32 = 4;
pub const VALUE_POINT: u32 = 5;
pub const VALUE_TEXT: u32 = 6;

/// A picture: `height` rows of `stride` bytes, `width` pixels of 4 bytes used in each.
#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct RawFrame {
    pub data: *mut u8,
    pub width: u32,
    pub height: u32,
    pub stride: u32,
    /// [`FORMAT_RGBA8_PREMULTIPLIED`].
    pub format: u32,
}

/// A parameter value. Numbers, integers, toggles (0 or 1) and choices (an index) use
/// `numbers[0]`; colours `numbers[0..4]` (straight sRGB 0…1); points `numbers[0..2]`; text and
/// file paths `text` (UTF-8, `text_len` bytes, not NUL-terminated).
#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct RawValue {
    pub kind: u32,
    pub reserved: u32,
    pub numbers: [f64; 4],
    pub text: *const u8,
    pub text_len: usize,
}

impl RawValue {
    fn with(kind: u32, numbers: [f64; 4]) -> Self {
        Self { kind, reserved: 0, numbers, text: std::ptr::null(), text_len: 0 }
    }

    pub fn number(n: f64) -> Self {
        Self::with(VALUE_NUMBER, [n, 0.0, 0.0, 0.0])
    }

    pub fn integer(n: i64) -> Self {
        Self::with(VALUE_INTEGER, [n as f64, 0.0, 0.0, 0.0])
    }

    pub fn toggle(on: bool) -> Self {
        Self::with(VALUE_TOGGLE, [on as u8 as f64, 0.0, 0.0, 0.0])
    }

    pub fn choice(index: usize) -> Self {
        Self::with(VALUE_CHOICE, [index as f64, 0.0, 0.0, 0.0])
    }

    pub fn color(c: [f32; 4]) -> Self {
        Self::with(VALUE_COLOR, c.map(f64::from))
    }

    pub fn point(p: [f32; 2]) -> Self {
        Self::with(VALUE_POINT, [p[0] as f64, p[1] as f64, 0.0, 0.0])
    }

    /// Borrows `text`: keep it alive until the call that takes this value returns.
    pub fn text(text: &str) -> Self {
        Self { text: text.as_ptr(), text_len: text.len(), ..Self::with(VALUE_TEXT, [0.0; 4]) }
    }

    /// A plugin-side value as it crosses the ABI (borrows its text).
    pub fn of(value: &Value) -> Self {
        match *value {
            Value::Number(n) => Self::number(n),
            Value::Integer(i) => Self::integer(i),
            Value::Toggle(b) => Self::toggle(b),
            Value::Choice(i) => Self::choice(i),
            Value::Color(c) => Self::color(c),
            Value::Point(p) => Self::point(p),
            Value::Text(t) => Self::text(t),
        }
    }
}

/// What an instance is made for (see [`Setup`]).
#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct RawSetup {
    /// `size_of::<RawSetup>()` as the host was built.
    pub size: u32,
    pub width: u32,
    pub height: u32,
    pub reserved: u32,
    pub fps: f64,
}

impl RawSetup {
    pub fn new(width: u32, height: u32, fps: f64) -> Self {
        Self { size: size_of::<Self>() as u32, width, height, reserved: 0, fps }
    }
}

/// A job for [`RawHost::parallel`]: called with the `data` given and every index.
pub type Job = unsafe extern "C" fn(data: *mut c_void, index: u32);

/// Services the host lends a plugin during `render`. Hosts may embed it at the start of a larger
/// struct of their own: every function gets the `RawHost` pointer back.
#[repr(C)]
pub struct RawHost {
    /// `size_of::<RawHost>()` as the host was built.
    pub size: u32,
    pub reserved: u32,
    /// Calls `job(data, i)` for every `i` in `0..count`, on any of the host's threads, and returns
    /// once all have returned. The jobs must not panic across it (the SDK catches them).
    pub parallel: unsafe extern "C" fn(host: *const RawHost, count: u32, job: Job, data: *mut c_void),
    /// A line for the host's log: `level` 0 error, 1 warning, 2 info, 3 debug.
    pub log: unsafe extern "C" fn(host: *const RawHost, level: u32, message: *const u8, len: usize),
}

/// What a frame is drawn for (see [`RenderCtx`]).
#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct RawRenderCtx {
    /// `size_of::<RawRenderCtx>()` as the host was built.
    pub size: u32,
    /// 1 for a fast preview frame.
    pub draft: u32,
    pub time: f64,
    pub fps: f64,
    pub scale: f32,
    pub progress: f32,
    /// May be null.
    pub host: *const RawHost,
}

impl RawRenderCtx {
    pub fn new(time: f64, fps: f64, scale: f32, progress: f32, draft: bool, host: *const RawHost) -> Self {
        Self { size: size_of::<Self>() as u32, draft: draft as u32, time, fps, scale, progress, host }
    }
}

/// One plugin type. Hosts call only the functions that fit in `size`.
#[repr(C)]
pub struct PluginVTable {
    /// `size_of::<PluginVTable>()` as the plugin was built.
    pub size: u32,
    /// Writes the [`Manifest`] as JSON into a buffer the host frees with `free_bytes`.
    pub manifest: unsafe extern "C" fn(out: *mut *mut u8, len: *mut usize) -> i32,
    pub free_bytes: unsafe extern "C" fn(ptr: *mut u8, len: usize),
    /// A new instance, or null if making it failed (the plugin panicked).
    pub create: unsafe extern "C" fn(setup: *const RawSetup) -> *mut c_void,
    pub destroy: unsafe extern "C" fn(instance: *mut c_void),
    /// Sets parameter `index` (its place in the manifest's list).
    pub set_param: unsafe extern "C" fn(instance: *mut c_void, index: u32, value: *const RawValue) -> i32,
    /// Draws `output` from `input_count` inputs, all the same size as it.
    pub render: unsafe extern "C" fn(instance: *mut c_void, inputs: *const RawFrame, input_count: u32, output: *const RawFrame, ctx: *const RawRenderCtx) -> i32,
    /// Why the last call failed, as UTF-8 in a buffer freed with `free_bytes` (empty if none).
    pub last_error: unsafe extern "C" fn(instance: *mut c_void, out: *mut *mut u8, len: *mut usize) -> i32,
}

// Vtables are tables of plain function pointers.
unsafe impl Sync for PluginVTable {}
unsafe impl Send for PluginVTable {}

/// The root of a plugin library, returned by `kimchi_plugin_entry`.
#[repr(C)]
pub struct Entry {
    /// [`ABI_VERSION`] of the SDK the library was built with.
    pub abi_version: u32,
    pub plugin_count: u32,
    pub plugin: unsafe extern "C" fn(index: u32) -> *const PluginVTable,
}

unsafe impl Sync for Entry {}
unsafe impl Send for Entry {}

/// The type of `kimchi_plugin_entry`.
pub type EntryFn = unsafe extern "C" fn() -> *const Entry;

// ABI 1 is frozen: a change that moves any of these fails to compile.
const _: () = {
    use std::mem::offset_of;
    let pointer = size_of::<usize>();
    assert!(offset_of!(Entry, plugin_count) == 4 && offset_of!(Entry, plugin) == 8);
    assert!(offset_of!(PluginVTable, manifest) == pointer);
    assert!(offset_of!(PluginVTable, render) == 6 * pointer);
    assert!(size_of::<PluginVTable>() == 8 * pointer);
    assert!(offset_of!(RawFrame, width) == pointer && offset_of!(RawFrame, format) == pointer + 12);
    assert!(offset_of!(RawValue, numbers) == 8 && offset_of!(RawValue, text) == 40);
    assert!(size_of::<RawSetup>() == 24 && offset_of!(RawSetup, fps) == 16);
    assert!(offset_of!(RawHost, parallel) == 8 && offset_of!(RawHost, log) == 8 + pointer);
    assert!(offset_of!(RawRenderCtx, time) == 8 && offset_of!(RawRenderCtx, scale) == 24 && offset_of!(RawRenderCtx, host) == 32);
};

/// A plugin's metadata as it crosses the ABI.
#[derive(Clone, Debug, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct Manifest {
    pub abi: u32,
    pub id: String,
    pub name: String,
    pub vendor: String,
    #[serde(default)]
    pub version: String,
    #[serde(default)]
    pub category: String,
    #[serde(default)]
    pub description: String,
    pub kind: Kind,
    #[serde(default)]
    pub animated: bool,
    #[serde(default)]
    pub params: Vec<ManifestParam>,
}

/// One parameter in a [`Manifest`].
#[derive(Clone, Debug, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct ManifestParam {
    pub name: String,
    #[serde(default)]
    pub label: String,
    pub kind: ParamKind,
    /// A number, true/false, `[r, g, b, a]`, `[x, y]` or text, by kind.
    pub default: serde_json::Value,
    #[serde(default)]
    pub min: f64,
    #[serde(default)]
    pub max: f64,
    #[serde(default)]
    pub unit: String,
    #[serde(default)]
    pub choices: Vec<String>,
    #[serde(default)]
    pub extensions: Vec<String>,
    #[serde(default)]
    pub group: String,
    #[serde(default)]
    pub hint: String,
}

impl Manifest {
    pub fn of<P: Plugin>() -> Self {
        let i = P::INFO;
        Self {
            abi: ABI_VERSION,
            id: i.id.into(),
            name: i.name.into(),
            vendor: i.vendor.into(),
            version: i.version.into(),
            category: i.category.into(),
            description: i.description.into(),
            kind: i.kind,
            animated: i.animated,
            params: P::params().iter().map(ManifestParam::of).collect(),
        }
    }

    /// Everything a host relies on: an id that is `com.vendor.name`-like, a name, and parameters
    /// with unique names, sane ranges, defaults of their kind inside them, and choices to choose.
    pub fn validate(&self) -> Result<(), String> {
        let id_ok = !self.id.is_empty()
            && self.id.contains('.')
            && self.id.chars().all(|c| c.is_ascii_alphanumeric() || matches!(c, '.' | '-' | '_'))
            && !self.id.starts_with('.')
            && !self.id.ends_with('.');
        if !id_ok {
            return Err(format!("Plugin id `{}` should be reverse-DNS like `com.vendor.name` (letters, digits, dots, - and _).", self.id));
        }
        if self.name.trim().is_empty() {
            return Err(format!("Plugin `{}` has no name.", self.id));
        }
        let mut seen = std::collections::HashSet::new();
        for p in &self.params {
            let what = format!("Parameter `{}` of `{}`", p.name, self.id);
            if p.name.trim().is_empty() || p.name.contains('.') {
                return Err(format!("{what}: names can't be empty or contain dots (keyframes are named plugins.<slot>.<name>)."));
            }
            if !seen.insert(p.name.as_str()) {
                return Err(format!("{what} is declared twice."));
            }
            let ranged = matches!(p.kind, ParamKind::Number | ParamKind::Integer | ParamKind::Angle | ParamKind::Choice);
            if ranged && (!p.min.is_finite() || !p.max.is_finite() || p.min > p.max) {
                return Err(format!("{what} has an invalid range {}…{}.", p.min, p.max));
            }
            let d = &p.default;
            let ok = match p.kind {
                ParamKind::Number | ParamKind::Integer | ParamKind::Angle | ParamKind::Choice => d.as_f64().is_some_and(|v| v >= p.min && v <= p.max),
                ParamKind::Toggle => d.is_boolean(),
                ParamKind::Color => d.as_array().is_some_and(|a| a.len() == 4 && a.iter().all(|v| v.as_f64().is_some_and(|v| (0.0..=1.0).contains(&v)))),
                ParamKind::Point => d.as_array().is_some_and(|a| a.len() == 2 && a.iter().all(|v| v.as_f64().is_some_and(f64::is_finite))),
                ParamKind::Text | ParamKind::File => d.is_string(),
            };
            if !ok {
                return Err(format!("{what}: its default {d} doesn't fit a {:?} parameter (or is out of its range).", p.kind));
            }
            if p.kind == ParamKind::Choice && p.choices.is_empty() {
                return Err(format!("{what} is a choice with nothing to choose."));
            }
        }
        Ok(())
    }
}

impl ManifestParam {
    pub fn of(p: &Param) -> Self {
        let default = match p.default {
            Initial::Number(n) => serde_json::json!(n),
            Initial::Toggle(b) => serde_json::json!(b),
            Initial::Color(c) => serde_json::json!(c.map(|v| v as f64)),
            Initial::Point(pt) => serde_json::json!(pt.map(|v| v as f64)),
            Initial::Text(t) => serde_json::json!(t),
        };
        Self {
            name: p.name.into(),
            label: if p.label.is_empty() { p.name.into() } else { p.label.into() },
            kind: p.kind,
            default,
            min: p.min,
            max: p.max,
            unit: p.unit.into(),
            choices: p.choices.iter().map(|c| c.to_string()).collect(),
            extensions: p.extensions.iter().map(|c| c.to_string()).collect(),
            group: p.group.into(),
            hint: p.hint.into(),
        }
    }
}

// ---- the plugin side ------------------------------------------------------------------------

/// A panic's message.
fn panic_message(payload: &(dyn Any + Send)) -> String {
    payload.downcast_ref::<&str>().map(|s| s.to_string()).or_else(|| payload.downcast_ref::<String>().cloned()).unwrap_or_else(|| "a panic without a message".into())
}

/// What an instance pointer points at.
struct Guarded<P> {
    plugin: P,
    params: Vec<Param>,
    poisoned: bool,
    error: String,
}

impl<P> Guarded<P> {
    /// Runs `f` on the plugin unless it is poisoned; a panic poisons it.
    fn run(&mut self, f: impl FnOnce(&mut P)) -> i32 {
        if self.poisoned {
            return STATUS_POISONED;
        }
        match std::panic::catch_unwind(AssertUnwindSafe(|| f(&mut self.plugin))) {
            Ok(()) => STATUS_OK,
            Err(payload) => {
                self.poisoned = true;
                self.error = format!("panicked: {}", panic_message(payload.as_ref()));
                STATUS_PANICKED
            }
        }
    }

    fn invalid(&mut self, why: String) -> i32 {
        self.error = why;
        STATUS_INVALID
    }
}

unsafe fn give(bytes: Vec<u8>, out: *mut *mut u8, len: *mut usize) -> i32 {
    if out.is_null() || len.is_null() {
        return STATUS_INVALID;
    }
    let boxed = bytes.into_boxed_slice();
    // SAFETY: checked non-null above; the host passes writable pointers.
    unsafe {
        *len = boxed.len();
        *out = Box::into_raw(boxed) as *mut u8;
    }
    STATUS_OK
}

unsafe extern "C" fn manifest<P: Plugin>(out: *mut *mut u8, len: *mut usize) -> i32 {
    match std::panic::catch_unwind(|| serde_json::to_vec(&Manifest::of::<P>())) {
        // SAFETY: the host's pointers, checked in `give`.
        Ok(Ok(bytes)) => unsafe { give(bytes, out, len) },
        _ => STATUS_PANICKED,
    }
}

unsafe extern "C" fn free_bytes(ptr: *mut u8, len: usize) {
    if !ptr.is_null() {
        // SAFETY: made by `give` from a boxed slice of `len` bytes.
        drop(unsafe { Box::from_raw(std::ptr::slice_from_raw_parts_mut(ptr, len)) });
    }
}

unsafe extern "C" fn create<P: Plugin>(setup: *const RawSetup) -> *mut c_void {
    let setup = if setup.is_null() {
        Setup { width: 0, height: 0, fps: 30.0 }
    } else {
        // SAFETY: non-null, and every field of ABI 1's RawSetup is there.
        let s = unsafe { &*setup };
        Setup { width: s.width, height: s.height, fps: if s.fps.is_finite() && s.fps > 0.0 { s.fps } else { 30.0 } }
    };
    match std::panic::catch_unwind(|| Box::new(Guarded { plugin: P::new(&setup), params: P::params(), poisoned: false, error: String::new() })) {
        Ok(g) => Box::into_raw(g) as *mut c_void,
        Err(_) => std::ptr::null_mut(),
    }
}

unsafe extern "C" fn destroy<P: Plugin>(instance: *mut c_void) {
    if !instance.is_null() {
        // SAFETY: made by `create::<P>`.
        let _ = std::panic::catch_unwind(AssertUnwindSafe(|| drop(unsafe { Box::from_raw(instance as *mut Guarded<P>) })));
    }
}

/// `raw` as a value of `param`'s kind, in its range. Numbers convert between number kinds;
/// anything else of the wrong kind is refused.
fn coerce<'a>(param: &Param, raw: &RawValue, text: &'a str) -> Result<Value<'a>, String> {
    let n = raw.numbers[0];
    let numeric = matches!(raw.kind, VALUE_NUMBER | VALUE_INTEGER | VALUE_TOGGLE | VALUE_CHOICE);
    let finite = |v: f64, fallback: f64| if v.is_finite() { v } else { fallback };
    let fallback = match param.default {
        Initial::Number(d) => d,
        _ => 0.0,
    };
    let wrong = || format!("`{}` takes a {:?} value, not value kind {}", param.name, param.kind, raw.kind);
    Ok(match param.kind {
        ParamKind::Number | ParamKind::Angle if numeric => Value::Number(finite(n, fallback).clamp(param.min, param.max)),
        ParamKind::Integer if numeric => Value::Integer(finite(n, fallback).round().clamp(param.min, param.max) as i64),
        ParamKind::Toggle if numeric => Value::Toggle(finite(n, 0.0) >= 0.5),
        ParamKind::Choice if numeric => Value::Choice(finite(n, fallback).round().clamp(param.min, param.max).max(0.0) as usize),
        ParamKind::Color if raw.kind == VALUE_COLOR => Value::Color(raw.numbers.map(|v| finite(v, 0.0).clamp(0.0, 1.0) as f32)),
        ParamKind::Point if raw.kind == VALUE_POINT => Value::Point([finite(raw.numbers[0], 0.5) as f32, finite(raw.numbers[1], 0.5) as f32]),
        ParamKind::Text | ParamKind::File if raw.kind == VALUE_TEXT => Value::Text(text),
        _ => return Err(wrong()),
    })
}

unsafe extern "C" fn set_param<P: Plugin>(instance: *mut c_void, index: u32, value: *const RawValue) -> i32 {
    if instance.is_null() {
        return STATUS_INVALID;
    }
    // SAFETY: made by `create::<P>`; the host calls one function at a time on an instance.
    let g = unsafe { &mut *(instance as *mut Guarded<P>) };
    if value.is_null() {
        return g.invalid("set_param got no value".into());
    }
    // SAFETY: non-null; the host's value lives for the call.
    let raw = unsafe { &*value };
    let Some(param) = g.params.get(index as usize).copied() else {
        return g.invalid(format!("{} has no parameter {index} (it has {})", P::INFO.name, g.params.len()));
    };
    let text = if raw.kind == VALUE_TEXT && !raw.text.is_null() && raw.text_len > 0 {
        // SAFETY: the host passes `text_len` readable bytes.
        let bytes = unsafe { std::slice::from_raw_parts(raw.text, raw.text_len) };
        match std::str::from_utf8(bytes) {
            Ok(t) => t,
            Err(_) => return g.invalid(format!("`{}` got text that isn't UTF-8", param.name)),
        }
    } else {
        ""
    };
    match coerce(&param, raw, text) {
        Ok(v) => g.run(|p| p.set_param(index as usize, v)),
        Err(e) => g.invalid(e),
    }
}

unsafe extern "C" fn render<P: Plugin>(instance: *mut c_void, inputs: *const RawFrame, input_count: u32, output: *const RawFrame, ctx: *const RawRenderCtx) -> i32 {
    if instance.is_null() {
        return STATUS_INVALID;
    }
    // SAFETY: made by `create::<P>`.
    let g = unsafe { &mut *(instance as *mut Guarded<P>) };
    if g.poisoned {
        return STATUS_POISONED;
    }
    if output.is_null() || ctx.is_null() || (inputs.is_null() && input_count > 0) {
        return g.invalid("render got a null frame or context".into());
    }
    let want = match P::INFO.kind {
        Kind::Effect => 1,
        Kind::Generator => 0,
        Kind::Transition => 2,
    };
    if (input_count as usize) < want {
        return g.invalid(format!("{} needs {want} input frame(s), got {input_count}", P::INFO.name));
    }
    // SAFETY: non-null, `input_count` frames.
    let raw_inputs = if input_count == 0 { &[][..] } else { unsafe { std::slice::from_raw_parts(inputs, input_count as usize) } };
    // SAFETY: non-null.
    let (out, raw_ctx) = unsafe { (&*output, &*ctx) };
    for f in raw_inputs.iter().chain([out]) {
        if f.data.is_null() || f.format != FORMAT_RGBA8_PREMULTIPLIED || (f.stride as u64) < f.width as u64 * 4 {
            return g.invalid(format!("a frame is null, of an unknown format ({}) or its rows are too short", f.format));
        }
        if f.width != out.width || f.height != out.height {
            return g.invalid(format!("frames differ in size: {}×{} and {}×{}", f.width, f.height, out.width, out.height));
        }
    }
    let len = |f: &RawFrame| if f.height == 0 { 0 } else { (f.height as usize - 1) * f.stride as usize + f.width as usize * 4 };
    // SAFETY: the host lends each input's bytes for reading and the output's for writing, for
    // the length of the call; the output doesn't overlap an input.
    let frames: Vec<Frame> = raw_inputs.iter().map(|f| Frame::new(unsafe { std::slice::from_raw_parts(f.data, len(f)) }, f.width as usize, f.height as usize, f.stride as usize)).collect();
    let mut target = FrameMut::new(unsafe { std::slice::from_raw_parts_mut(out.data, len(out)) }, out.width as usize, out.height as usize, out.stride as usize);
    let fits = |end: usize| raw_ctx.size as usize >= end;
    let host = if fits(size_of::<RawRenderCtx>()) && !raw_ctx.host.is_null() {
        // SAFETY: non-null; the host's services live for the call.
        let h = unsafe { &*raw_ctx.host };
        (h.size as usize >= size_of::<RawHost>()).then_some(h)
    } else {
        None
    };
    let rc = RenderCtx {
        time: if raw_ctx.time.is_finite() { raw_ctx.time } else { 0.0 },
        fps: if raw_ctx.fps.is_finite() && raw_ctx.fps > 0.0 { raw_ctx.fps } else { 30.0 },
        scale: if raw_ctx.scale.is_finite() && raw_ctx.scale > 0.0 { raw_ctx.scale } else { 1.0 },
        progress: if raw_ctx.progress.is_finite() { raw_ctx.progress.clamp(0.0, 1.0) } else { 0.0 },
        draft: raw_ctx.draft != 0,
        host,
    };
    g.run(|p| p.render(&frames, &mut target, &rc))
}

unsafe extern "C" fn last_error<P: Plugin>(instance: *mut c_void, out: *mut *mut u8, len: *mut usize) -> i32 {
    if instance.is_null() {
        return STATUS_INVALID;
    }
    // SAFETY: made by `create::<P>`.
    let g = unsafe { &*(instance as *const Guarded<P>) };
    // SAFETY: the host's pointers, checked in `give`.
    unsafe { give(g.error.clone().into_bytes(), out, len) }
}

/// The vtable for one plugin type. Usable in `static` tables.
pub const fn vtable<P: Plugin>() -> PluginVTable {
    PluginVTable {
        size: size_of::<PluginVTable>() as u32,
        manifest: manifest::<P>,
        free_bytes,
        create: create::<P>,
        destroy: destroy::<P>,
        set_param: set_param::<P>,
        render: render::<P>,
        last_error: last_error::<P>,
    }
}

/// Runs `job` over `0..count` on the host's threads (see [`RenderCtx::parallel`]).
pub(crate) fn parallel(host: Option<&RawHost>, count: usize, job: &(dyn Fn(usize) + Sync)) {
    let Some(host) = host.filter(|_| count > 1) else {
        (0..count).for_each(job);
        return;
    };
    struct Shared<'a> {
        job: &'a (dyn Fn(usize) + Sync),
        panic: Mutex<Option<Box<dyn Any + Send>>>,
    }
    unsafe extern "C" fn trampoline(data: *mut c_void, index: u32) {
        // SAFETY: `data` is the `Shared` below, alive until `parallel` returns.
        let shared = unsafe { &*(data as *const Shared) };
        if let Err(payload) = std::panic::catch_unwind(AssertUnwindSafe(|| (shared.job)(index as usize))) {
            shared.panic.lock().unwrap_or_else(|e| e.into_inner()).get_or_insert(payload);
        }
    }
    let shared = Shared { job, panic: Mutex::new(None) };
    // SAFETY: the host runs every job before returning; `shared` outlives the call.
    unsafe { (host.parallel)(host, count.min(u32::MAX as usize) as u32, trampoline, &shared as *const Shared as *mut c_void) };
    // A job's panic goes on in the render call, where the vtable catches it.
    if let Some(payload) = shared.panic.into_inner().unwrap_or_else(|e| e.into_inner()) {
        std::panic::resume_unwind(payload);
    }
}

pub(crate) fn log(host: Option<&RawHost>, level: u32, message: &str) {
    if let Some(h) = host {
        // SAFETY: the host's function, with the message's bytes for the call.
        unsafe { (h.log)(h, level, message.as_ptr(), message.len()) };
    }
}

// ---- the host side --------------------------------------------------------------------------

/// The plugins an entry exports, after checking its ABI version.
///
/// # Safety
/// `entry` must be what a library's `kimchi_plugin_entry` returned (or null), and the library
/// must stay loaded for as long as the tables are used.
pub unsafe fn tables(entry: *const Entry) -> Result<Vec<&'static PluginVTable>, String> {
    if entry.is_null() {
        return Err("The library's kimchi_plugin_entry returned nothing.".into());
    }
    // SAFETY: non-null, and the first two fields are the same in every ABI.
    let e = unsafe { &*entry };
    if e.abi_version != ABI_VERSION {
        let newer = if e.abi_version > ABI_VERSION { "a newer kimchi: update kimchi" } else { "an older kimchi-plugin: rebuild it with the current SDK" };
        return Err(format!("It was built for kimchi plugin ABI {}, and this kimchi knows ABI {ABI_VERSION} ({newer}).", e.abi_version));
    }
    if e.plugin_count == 0 || e.plugin_count > 1024 {
        return Err(format!("It says it has {} plugins.", e.plugin_count));
    }
    (0..e.plugin_count)
        .map(|i| {
            // SAFETY: an ABI 1 entry's function.
            let t = unsafe { (e.plugin)(i) };
            if t.is_null() {
                return Err(format!("Plugin {i} has no vtable."));
            }
            // SAFETY: non-null; `size` is the first field of every revision.
            let t = unsafe { &*t };
            if (t.size as usize) < size_of::<PluginVTable>() {
                return Err(format!("Plugin {i}'s vtable is {} bytes, ABI 1 needs {}.", t.size, size_of::<PluginVTable>()));
            }
            Ok(t)
        })
        .collect()
}

/// A vtable's manifest, checked ([`Manifest::validate`]).
pub fn read_manifest(table: &PluginVTable) -> Result<Manifest, String> {
    let mut ptr: *mut u8 = std::ptr::null_mut();
    let mut len = 0usize;
    // SAFETY: an ABI 1 function with pointers to our locals.
    let code = unsafe { (table.manifest)(&mut ptr, &mut len) };
    if code != STATUS_OK || ptr.is_null() {
        return Err(format!("The plugin couldn't describe itself (status {code})."));
    }
    // SAFETY: the plugin wrote `len` bytes there; it frees them.
    let bytes = unsafe { std::slice::from_raw_parts(ptr, len) }.to_vec();
    unsafe { (table.free_bytes)(ptr, len) };
    let m: Manifest = serde_json::from_slice(&bytes).map_err(|e| format!("Its description isn't readable: {e}"))?;
    if m.abi != ABI_VERSION {
        return Err(format!("Its description is for ABI {} (this kimchi knows {ABI_VERSION}).", m.abi));
    }
    m.validate()?;
    Ok(m)
}

/// An instance, from the host's side: made, given values, rendered and destroyed through the
/// vtable. Not shared between threads, but may move between them.
pub struct Handle {
    table: &'static PluginVTable,
    instance: *mut c_void,
}

// The plugin promises `Send` (the trait requires it); calls are never concurrent (`&mut self`).
unsafe impl Send for Handle {}

impl Handle {
    pub fn new(table: &'static PluginVTable, setup: &RawSetup) -> Result<Self, String> {
        // SAFETY: an ABI 1 function; `setup` lives for the call.
        let instance = unsafe { (table.create)(setup) };
        if instance.is_null() {
            return Err("The plugin failed to start (it panicked while being made).".into());
        }
        Ok(Self { table, instance })
    }

    fn check(&self, code: i32) -> Result<(), String> {
        match code {
            STATUS_OK => Ok(()),
            STATUS_POISONED => Err(format!("it stopped after an earlier error: {}", self.last_error())),
            _ => Err(self.last_error()),
        }
    }

    /// Why the last call failed.
    pub fn last_error(&self) -> String {
        let mut ptr: *mut u8 = std::ptr::null_mut();
        let mut len = 0usize;
        // SAFETY: our instance and locals.
        let code = unsafe { (self.table.last_error)(self.instance, &mut ptr, &mut len) };
        if code != STATUS_OK || ptr.is_null() {
            return "an unknown error".into();
        }
        // SAFETY: `len` bytes written by the plugin, freed by it.
        let text = String::from_utf8_lossy(unsafe { std::slice::from_raw_parts(ptr, len) }).into_owned();
        unsafe { (self.table.free_bytes)(ptr, len) };
        if text.is_empty() { "an unknown error".into() } else { text }
    }

    pub fn set_param(&mut self, index: u32, value: &RawValue) -> Result<(), String> {
        // SAFETY: our instance; the value (and its text) live for the call.
        let code = unsafe { (self.table.set_param)(self.instance, index, value) };
        self.check(code)
    }

    /// Draws `output` from `inputs`. The frames' memory must be valid for the call, and the
    /// output must not overlap an input.
    pub fn render(&mut self, inputs: &[RawFrame], output: &RawFrame, ctx: &RawRenderCtx) -> Result<(), String> {
        // SAFETY: our instance; frames and context live for the call.
        let code = unsafe { (self.table.render)(self.instance, inputs.as_ptr(), inputs.len() as u32, output, ctx) };
        self.check(code)
    }
}

impl Drop for Handle {
    fn drop(&mut self) {
        // SAFETY: made by this table's `create`, destroyed once.
        unsafe { (self.table.destroy)(self.instance) };
    }
}
